/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as OnboardingImport } from './routes/_onboarding'
import { Route as MainImport } from './routes/_main'
import { Route as OnboardingAuthImport } from './routes/_onboarding.auth'
import { Route as OnboardingAuthForgotPasswordImport } from './routes/_onboarding.auth.forgot-password'
import { Route as OnboardingSetupImport } from './routes/_onboarding.setup'
import { Route as MainHomeImport } from './routes/_main.home'
import { Route as MainMeetsImport } from './routes/_main.meets'
import { Route as MainConfessionsImport } from './routes/_main.confessions'
import { Route as MainUsImport } from './routes/_main.us'
import { Route as MainAboutImport } from './routes/_main.about'

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const OnboardingRoute = OnboardingImport.update({
  id: '/_onboarding',
  getParentRoute: () => rootRoute,
} as any)

const MainRoute = MainImport.update({
  id: '/_main',
  getParentRoute: () => rootRoute,
} as any)

const OnboardingAuthRoute = OnboardingAuthImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => OnboardingRoute,
} as any)

const OnboardingAuthForgotPasswordRoute = OnboardingAuthForgotPasswordImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => OnboardingRoute,
} as any)

const OnboardingSetupRoute = OnboardingSetupImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => OnboardingRoute,
} as any)

const MainHomeRoute = MainHomeImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => MainRoute,
} as any)

const MainMeetsRoute = MainMeetsImport.update({
  id: '/meets',
  path: '/meets',
  getParentRoute: () => MainRoute,
} as any)

const MainConfessionsRoute = MainConfessionsImport.update({
  id: '/confessions',
  path: '/confessions',
  getParentRoute: () => MainRoute,
} as any)

const MainUsRoute = MainUsImport.update({
  id: '/us',
  path: '/us',
  getParentRoute: () => MainRoute,
} as any)

const MainAboutRoute = MainAboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MainRoute,
} as any)

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  OnboardingRoute.addChildren([
    OnboardingAuthRoute,
    OnboardingAuthForgotPasswordRoute,
    OnboardingSetupRoute,
  ]),
  MainRoute.addChildren([
    MainHomeRoute,
    MainMeetsRoute,
    MainConfessionsRoute,
    MainUsRoute,
    MainAboutRoute,
  ]),
])
